jobs:
  bump-version:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out source
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - continue-on-error: true
      name: Setup Node.js
      uses: actions/setup-node@v3.5.1
      with:
        node-version: '16'
    - continue-on-error: true
      name: Setup Git
      run: 'git config user.name ''RNMapbox robot''

        git config user.email ''rnmapbox@gmail.com''

        '
    - continue-on-error: true
      name: bump version
      run: npm version ${{ github.event.inputs.version }}
    - continue-on-error: true
      name: Push latest version
      run: git push origin main --follow-tags
name: Bump version
on:
  repository_dispatch:
    types: trigger-ga___bump-version.yml
