jobs:
  check-issue-example-code:
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: run lint-code-example-in-issues.js
      run: 'npm install

        node lint-code-example-in-issues.js

        '
      working-directory: ./scripts/actions/lint-code-example-in-issues
name: CheckCodeExampleInIssue
on:
  repository_dispatch:
    types: trigger-ga___check-code-example-in-issue.yml
