concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref || github.run_id }}-ci-with-tokens
jobs:
  call_android_workflow:
    name: Android/Mapbox
    secrets:
      ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.ENV_MAPBOX_ACCESS_TOKEN }}
      ENV_MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.ENV_MAPBOX_DOWNLOAD_TOKEN }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
    uses: ./.github/workflows/android-actions.yml
    with:
      MAP_IMPL: mapbox
      NVMRC: ${{ inputs.NVMRC }}
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
  call_android_workflow_11:
    name: Android/Mapbox11
    secrets:
      ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.ENV_MAPBOX_ACCESS_TOKEN }}
      ENV_MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.ENV_MAPBOX_DOWNLOAD_TOKEN }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
    uses: ./.github/workflows/android-actions.yml
    with:
      MAP_IMPL: mapbox11
      NVMRC: ${{ inputs.NVMRC }}
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
  call_android_workflow_fabric:
    name: Android/Mapbox/Fabric
    secrets:
      ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.ENV_MAPBOX_ACCESS_TOKEN }}
      ENV_MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.ENV_MAPBOX_DOWNLOAD_TOKEN }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
    uses: ./.github/workflows/android-actions.yml
    with:
      MAP_IMPL: mapbox
      NEW_ARCH: true
      NVMRC: ${{ inputs.NVMRC }}
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
  call_ios_workflow:
    name: iOS/Mapbox
    secrets:
      ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.ENV_MAPBOX_ACCESS_TOKEN }}
      ENV_MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.ENV_MAPBOX_DOWNLOAD_TOKEN }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
    uses: ./.github/workflows/ios-actions.yml
    with:
      MAP_IMPL: mapbox
      NVMRC: ${{ inputs.NVMRC }}
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
  call_ios_workflow_11:
    name: iOS/Mapbox11
    secrets:
      ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.ENV_MAPBOX_ACCESS_TOKEN }}
      ENV_MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.ENV_MAPBOX_DOWNLOAD_TOKEN }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
    uses: ./.github/workflows/ios-actions.yml
    with:
      MAP_IMPL: mapbox11
      NVMRC: ${{ inputs.NVMRC }}
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
  call_ios_workflow_fabric:
    name: iOS/Mapbox/Fabric
    secrets:
      ENV_MAPBOX_ACCESS_TOKEN: ${{ secrets.ENV_MAPBOX_ACCESS_TOKEN }}
      ENV_MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.ENV_MAPBOX_DOWNLOAD_TOKEN }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
    uses: ./.github/workflows/ios-actions.yml
    with:
      MAP_IMPL: mapbox
      NEW_ARCH: true
      NVMRC: ${{ inputs.NVMRC }}
      env_name: ${{ inputs.env_name }}
      ref: ${{ inputs.ref }}
name: CI Builds requiring mapbox tokens
on:
  repository_dispatch:
    types: trigger-ga___ci-requiring-tokens.yml
