jobs:
  action:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dessant/label-actions@v2
name: Label Actions
on:
  repository_dispatch:
    types: trigger-ga___label-actions.yml
permissions:
  contents: read
  issues: write
