concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref || github.run_id }}
jobs:
  call_ci_requiring_tokens:
    if: needs.has_mapbox_token.outputs.has-mapbox-token == 'true'
    name: CI requiring tokens
    needs:
    - lint_test_generate
    - has_mapbox_token
    secrets:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      MAPBOX_DOWNLOAD_TOKEN: ${{ secrets.MAPBOX_DOWNLOAD_TOKEN }}
    uses: ./.github/workflows/ci-requiring-tokens.yml
    with:
      NVMRC: ${{ needs.lint_test_generate.outputs.NVMRC }}
  has_mapbox_token:
    outputs:
      has-mapbox-token: ${{ steps.has-mapbox-token.outputs.defined }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      id: has-mapbox-token
      if: ${{ env.MAPBOX_ACCESS_TOKEN != '' }}
      run: echo "::set-output name=defined::true"
  lint_test_generate:
    outputs:
      NVMRC: ${{ steps.nvm.outputs.NVMRC }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      id: nvm
      name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
    - continue-on-error: true
      name: Setup node ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v3.5.1
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}
    - continue-on-error: true
      name: Install
      run: yarn install --network-timeout 1000000
    - continue-on-error: true
      name: Lint
      run: yarn lint
    - continue-on-error: true
      name: Type check
      run: yarn type:check
    - continue-on-error: true
      name: Example/install
      run: yarn install --ignore-scripts --network-timeout 1000000
      working-directory: example
    - continue-on-error: true
      name: Example type check
      run: yarn type:check
      working-directory: example
    - continue-on-error: true
      name: Test
      run: yarn unittest
    - continue-on-error: true
      name: Generate
      run: yarn generate
  publish:
    if: startsWith(github.ref, 'refs/tags/') && (github.event_name == 'push')
    needs:
    - lint_test_generate
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup node ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v3.5.1
      with:
        node-version: ${{ needs.lint_test_generate.outputs.NVMRC }}
        registry-url: https://registry.npmjs.org/
    - continue-on-error: true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      name: Install and Publish
      run: npm install --force && npm publish
name: CI
on:
  repository_dispatch:
    types: trigger-ga___on-push.yml
