jobs:
  update_docs:
    defaults:
      run:
        working-directory: maps
    name: Update docs on maps-docs repo
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install ImageMagick
      run: sudo apt-get install -y imagemagick
      working-directory: /
    - continue-on-error: true
      name: test convert
      run: convert -version
      working-directory: /
    - continue-on-error: true
      name: Checkout maps repo
      uses: actions/checkout@v4
      with:
        path: maps
    - continue-on-error: true
      name: Checkout maps-docs repo
      uses: actions/checkout@v4
      with:
        path: maps-docs
        repository: rnmapbox/maps-docs
        ssh-key: ${{ secrets.MAPS_DOCS_DEPLOY_KEY }}
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - continue-on-error: true
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - continue-on-error: true
      name: Install dependencies
      run: yarn install
    - continue-on-error: true
      name: Generate component docs into maps-docs repo
      run: node scripts/doc-generate.mjs
    - continue-on-error: true
      name: Generate example docs into maps-docs repo
      run: bun scripts/example-docs.ts
    - continue-on-error: true
      name: Setup deploy key for github deploy
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.MAPS_DOCS_DEPLOY_KEY }}
    - continue-on-error: true
      env:
        GITHUB_SHA: ${{ github.sha }}
      name: Add all changed files to git and push to origin main
      run: 'git config --global user.name "github-actions[bot]"

        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add .

        git commit -m "Update docs from maps  rnmapbox/maps@${GITHUB_SHA::7}"

        git push origin main

        '
      working-directory: maps-docs
name: Update docs to maps-docs repo
on:
  repository_dispatch:
    types: trigger-ga___update-docs.yml
